# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-05 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelistTournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='duelist',
            name='draw',
            field=models.IntegerField(default=0, verbose_name='\u5f15\u304d\u5206\u3051\u6570'),
        ),
        migrations.AddField(
            model_name='duelist',
            name='lose',
            field=models.IntegerField(default=0, verbose_name='\u8ca0\u3051\u6570'),
        ),
        migrations.AddField(
            model_name='duelist',
            name='win',
            field=models.IntegerField(default=0, verbose_name='\u52dd\u3061\u6570'),
        ),
        migrations.AddField(
            model_name='duelisttournament',
            name='duelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelistTournaments', to='cms.Duelist', verbose_name='\u53c2\u52a0\u8005'),
        ),
        migrations.AddField(
            model_name='duelisttournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelistTournaments', to='cms.Tournament', verbose_name='\u5927\u4f1a'),
        ),
    ]
