# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20171009_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='duelist',
            name='mailAddress',
            field=models.CharField(default='', max_length=100, verbose_name='\u30e1\u30fc\u30eb\u30a2\u30c9\u30ec\u30b9'),
        ),
        migrations.AddField(
            model_name='duelist',
            name='passward',
            field=models.CharField(default='', max_length=30, verbose_name='\u30d1\u30b9\u30ef\u30fc\u30c9'),
        ),
        migrations.AlterField(
            model_name='duelisttournament',
            name='duelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelistTournaments', to='cms.Duelist', verbose_name='\u53c2\u52a0\u8005'),
        ),
        migrations.AlterField(
            model_name='duelisttournament',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duelistTournaments', to='cms.Tournament', verbose_name='\u5927\u4f1a'),
        ),
    ]
